# Generated by Django 4.2.24 on 2025-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relecloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(default="none"),
            preserve_default=False,
        ),
    ]
