# Generated by Django 4.2.24 on 2025-09-23 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relecloud", "0004_inforequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="slug",
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="destinations/"),
        ),
        migrations.AlterField(
            model_name="cruise",
            name="destinations",
            field=models.ManyToManyField(
                related_name="cruises", to="relecloud.destination"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True, max_length=1000)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Calificación debe estar entre 1 y 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "cruise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="relecloud.cruise",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="relecloud.destination",
                    ),
                ),
            ],
        ),
    ]
