# Generated by Django 4.2.24 on 2025-09-23 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("relecloud", "0005_remove_destination_slug_destination_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="image",
        ),
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cruise",
            name="destinations",
            field=models.ManyToManyField(
                related_name="destinations", to="relecloud.destination"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
