# Generated by Django 5.1.1 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_remove_destination_image_destination_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del destino', null=True, upload_to='destinations/'),
        ),
    ]
