# Generated by Django 4.2.26 on 2025-12-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0008_review_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
