# Generated by Django 5.1.1 on 2025-12-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
    ]
