trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.11'

steps:  
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    source venv/bin/activate
    python manage.py migrate
    python manage.py test
  displayName: 'Ejecutar pruebas'
  env:
    POSTGRES_DB: $(POSTGRES_DB)
    POSTGRES_USER: $(POSTGRES_USER)
    POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    POSTGRES_HOST: $(POSTGRES_HOST)
    DJANGO_SECRET_KEY: $(DJANGO_SECRET_KEY)
    DEBUG: 'False'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'TuServiceConnectionAzure'
    appName: 'NombreDeTuAppService'
    package: '$(System.DefaultWorkingDirectory)'